### PR TITLE
Fix: Ensure ws client is reset before re-connecting

### LINKED ISSUE #291: [WS2] Error: already open
Hello,

we just received couple of this errors:

```
{
  "stack": [
    "Error: already open",
    "    at WSv2.open (/path/node_modules/bitfinex-api-node/lib/transports/ws2.js:123:29)",
    "    at WebSocket._ws.once (/path/node_modules/bitfinex-api-node/lib/transports/ws2.js:225:14)",
    "    at Object.onceWrapper (events.js:255:19)",
    "    at WebSocket.emit (events.js:165:20)",
    "    at WebSocket.emitClose (/path/node_modules/ws/lib/WebSocket.js:211:10)",
    "    at _receiver.cleanup (/path/node_modules/ws/lib/WebSocket.js:199:39)",
    "    at Receiver.cleanup (/path/node_modules/ws/lib/Receiver.js:520:15)",
    "    at WebSocket.finalize (/path/node_modules/ws/lib/WebSocket.js:199:20)",
    "    at TLSSocket.emit (events.js:165:20)",
    "    at endReadableNT (_stream_readable.js:1101:12)",
    "    at process._tickCallback (internal/process/next_tick.js:152:19)"
  ],
  "message": "already open"
}
```

It looks like the reconnect does not always work properly. (we enabled autoreconnect feature)

Any idea what can be wrong?

### PR DESCRIPTION
**Pull request by f3rno**
I also added in `isReconnecting()` & updated the flag internally, since it was unused before. Closes #291 

Previously, `_isOpen` would have been `true` if the `_onWSClose()` handler didn't have a chance to fire.

### CODE REVIEW

File: test/lib/transports/ws2-unit.js [hunk 1]
```diff
@@ -120,6 +120,26 @@ describe('WSv2 lifetime', () => {
...
+    ws.on('open', () => {
+      assert(ws._ws !== null)
+      assert(ws._isOpen)
+
+      ws.close().then(() => {
+        assert(ws._ws == null)
+        assert(!ws._isOpen)
+
+        wss.close()
+        done()
```
Comment (robertkowalski) [inline test/lib/transports/ws2-unit.js]: <3
