### PR TITLE
Fix: Funding trade event routing 3.0.3

### LINKED ISSUE #456: onFundingTradeEntry and onFundingTradeUpdate don't work
The `fte` and `ftu` messages end up in `_handleTradeMessage`, but this has nothing specific to handle funding trades. As a result they are pushed out to `onTrades()` only.

### PR DESCRIPTION
**Pull request by f3rno**
Properly route `fte`/`ftu` messages to their respective handlers, closes #456

* [x] tests
* [x] version bumped
* [x] changelog bumped

### CODE REVIEW

File: lib/transports/ws2.js [hunk 1]
```diff
@@ -1782,13 +1792,17 @@ class WSv2 extends EventEmitter {
...
    * @param {Method} cb
    * @see https://docs.bitfinex.com/v2/reference#ws-public-trades
    */
-  onTrades ({ symbol, cbGID }, cb) {
-    this._registerListener('trades', { 0: symbol }, PublicTrade, cbGID, cb)
+  onTrades ({ symbol, pair, cbGID }, cb) {
+    const id = pair || symbol || ''
+    const model = id[0] === 'f' ? FundingTrade : PublicTrade
+
+    this._registerListener('trades', { 0: id }, PublicTrade, cbGID, cb)
```
Comment (instabot42) [inline lib/transports/ws2.js]: `PublicTrade` here should probably be `model`. 
`model` is not referenced in the current code.

Comment (f3rno) [reply lib/transports/ws2.js]: It's there don't worry.

Comment (f3rno) [reply lib/transports/ws2.js]: Nice catch thanks :)

File: lib/transports/ws2.js [hunk 2]
```diff
@@ -2214,24 +2228,26 @@ class WSv2 extends EventEmitter {
...
+   * @param {string?} opts.pair
+   * @param {string?} opts.symbol
    * @param {string} opts.cbGID - callback group id
    * @param {Method} cb
    * @see https://docs.bitfinex.com/v2/reference#ws-auth-funding-trades
    */
-  onFundingTradeEntry ({ symbol, cbGID }, cb) {
-    this._registerListener('fte', { 1: symbol }, FundingTrade, cbGID, cb)
+  onFundingTradeEntry ({ pair, symbol, cbGID }, cb) {
+    this._registerListener('fte', { 0: pair || symbol }, FundingTrade, cbGID, cb)
```
Comment (JacobPlaster) [inline lib/transports/ws2.js]: Why use pair here? I thought a funding trade only returned a single symbol i.e `fUSD`?

Comment (f3rno) [reply lib/transports/ws2.js]: Good point; I'm not sure what I was thinking, refactored it now to use only `symbol`
