### PR TITLE
Fix: order CANCELED status typo, closes #258

### LINKED ISSUE #258: API returns `CANCELED` but the Node API status is `CANCELLED`
maker_ _node_examples_ws2_maker_js_ _node_ _node_examples_ws2_maker_js_ _149x57
project_ ___workspace_maker

### PR DESCRIPTION
**Pull request by f3rno**

### CODE REVIEW

File: lib/models/order.js [hunk 1]
```diff
@@ -329,7 +329,7 @@ class Order extends Model {
 Order.type = {}
 Order.status = {}
 
-const statuses = ['ACTIVE', 'EXECUTED', 'PARTIALLY FILLED', 'CANCELLED']
+const statuses = ['ACTIVE', 'EXECUTED', 'PARTIALLY FILLED', 'CANCELED']
```
Comment (robertkowalski) [inline lib/models/order.js]: same typo in other models?

example:

https://github.com/bitfinexcom/bitfinex-api-node/blob/2ebbe05f8c6bcec1d03c9eca99258be0f476678e/lib/models/funding_loan.js#L44
