### PR TITLE
v2 Refactor

### LINKED ISSUE #41: api proposal: constructor & options
Right now the main-entry point, `index.js` initiates both the websocket and rest clients. This is usually unnecessary, as users will go with the rest **or** the ws client and leads to side effects.

For instance, when initialising the class, and using the http client in an integration test, the websocket code will cause the node.js process to wait & listen and not to exit.

Proposal:

Return the initiated client depending which method is called. The API should support chaining.

```js
const bfx = require('bitfinex-api-node')
const client = new Bfx(options).http()

const cb = () => {}
client.tracker(cb)

// chaining:

new Bfx(options).http().tracker()
```

For websockets:

```js
const BFX = new Bfx(options)
const client = BFX.ws()
```

What do you think?

### LINKED ISSUE #79: WS2 transform only for public api endpoints?
I don't see transformation in authenticated endpoints.

### LINKED ISSUE #84: Provide an example to sort the orderbook
From https://github.com/bitfinexcom/bitfinex-api-node/issues/83:

It's not obvious that the data in the Hashmap is not sorted by price and that you need to create some kind of sorted lists in order to have a sorted list with the orderbook values.

Provide an additional method that takes the current data and merges it back into a list.

### LINKED ISSUE #87: Documentation update
I cant find anything in the documentation about how to submit or cancel orders?
Should provide some examples.

```
  bws.on('oc', (id) => {
    // ???
  }); 
```

### LINKED ISSUE #90: Feedback over fork implementations
Hey

I recently saw that this repository was a bit stale (but I guess was proved me wrong ;), and started doing some work on the library, you can find over at [this fork](https://github.com/HyperCubeProject/bitfinex-api-node/tree/lite).

To summarize what has been done:
- Removes the v1 clients: we don't really want to support them indefinitely and encourage people to switch to the newest API's. This would require a major release.
- Transform the rest client class into a simple factory and simplify internal logic
- Minor refactors of the ws client but still a class since it extends `EventEmitter`
- Integrates candles
- Integrates normalization process directly in the transformer
- Readme polishing

I understand that it's a good chunk of changes, so totally willing to discuss/adapt and send separate diffs.

### LINKED ISSUE #112: Websocket not open
I am getting "websocket not open" errors every few hours. If someone has made code to reconnect, perhaps submit a pull request? Otherwise my program just crashes. Do I just use a try-catch and try to call "ws.open()" again?

screen shot 2017-09-11 at 12 35 46

### LINKED ISSUE #114: docs!?
im new to node.js
this bitfinex-api-node
is not finished? or?
cant finds how to buy/sell...anything... except orderbook 
HELP!?

### LINKED ISSUE #138: Websocket connection silently stops receiving data
My orderbook websockets occasionally stop receiving data, similar to this error in the Go API: https://github.com/bitfinexcom/bitfinex-api-go/pull/30

I was wondering if there was an ability to set a timeout so that an error may be thrown when a message is not received for some time? Or better yet, if it could automatically reconnect when a message is not received after some time? 

Thanks

### LINKED ISSUE #144: Socket hung up error
I am connecting to bifinex socket and after a certain time, I get the socket hung up error. How to handle this error and reconnect to the socket. This can be a feature inside this library only.

ERROR:
```
Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

### LINKED ISSUE #151: Pass BFX opts through to transport constructors
In favour of https://github.com/bitfinexcom/bitfinex-api-node/pull/137 :)

### LINKED ISSUE #153: Example for submiting a limit order and tracking it
Hi,

I'm trying to write some code to submit a limit order and track it so that I can trigger another action when the order gets executed or cancel the order if it doesn't get executed after some time.

There is a code in the examples directory that shows how to submit an order and how to cancel it, but how can I track the status of that order at any time ?

### PR DESCRIPTION
**Pull request by f3rno**
closes #41 (implemented, BFX ws() and rest() methods)
closes #79 (implemented, auth transforms)
closes #84 (implemented, order book model)
closes #90 (mostly implemented, outdated fork)
closes #112 (added auto reconnect)
closes #114 (docs request)
closes #151 (implemented, bfx passes args to transports)
closes #144 (added auto reconnect)
closes #153 (added order example)
closes #87 (added order example)
closes #138 (added ws2 packet watchdog)

* rewrote ws2.js
  * auto-reconnect w/ timeout
  * packet watchdog to reconnect on stale connection
  * sequence number verification (emits 'error' on mismatch)
  * added support for packet serialization via model classes (with bundled high-level logic in some cases)
  * added high level listener methods with filter support (`ws.onOrderUpdate({ symbol: 'tBTCUSD' }, () =>`)
  * added auto order multi-op endpoint usage via `orderOpBufferDelay`
  * added subscription ref counting, to avoid sending duplicate `subscribe` packets
  * added `ws.onInfoMessage`, `ws.onMaintenanceStart`, etc helpers
* added live Order updates via the ws interface
  * via Promises (`ws.submitOrder(o).then(() => ...`)
  * via the order model itself (init w/ transport like `new Order({}, ws2)`)j
* refactor `index.js` constructor signature
  * all transports take the same args (1 obj, `apiKey`, `apiSecret`, etc..)
  * cache transports as requested (`bfx.rest(1)`, `bfx.rest(2)`, etc)

And more!

### CODE REVIEW

File: lib/mocks/ws_server.js [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+  }
+
+  _onClientMessage (ws, msgJSON) {
+    const msg = JSON.parse(msgJSON)
+
+    this.emit('message', ws, msg)
+
+    if (msg.event === 'auth') {
+      return this._handleAuthMessage(ws, msg)
+    } else if (msg.constructor.name === 'Array') {
```
Comment (robertkowalski) [inline lib/mocks/ws_server.js]: would prefer

```js
Array.isArray(msg)
```

if possible

File: lib/model.js [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+class Model extends EventEmitter {
+  constructor (data = {}) {
+    super()
+
+    if (data.constructor.name === 'Object') {
+      Object.assign(this, data)
+    } else if (data.constructor.name === 'Array') {
+      Object.assign(this, this.constructor.unserialize(data))
+    }
```
Comment (robertkowalski) [inline lib/model.js]: same here:

```js 
if (Array.isArray(data)) {
  return Object.assign(this, this.constructor.unserialize(data))
}

Object.assign(this, data)
```

File: lib/models/order.js [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+      this.notify ? 1 : 0,
+      this.hidden ? 1 : 0,
+      this.placedId
+    ]
+  }
+
+  toNewOrderPacket () {
+    return {
+      gid: this.gid,
+      cid: this.cid || lastCID++,
```
Comment (robertkowalski) [inline lib/models/order.js]: lastCID is undefined

File: lib/models/order_book.js [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+    if (count === 0) {
+      for (let i = 0; i < side.length; i++) {
+        if (side[i][0] === price) {
+          side.splice(i, 1)
+          return
+        }
+      }
+
+      throw new Error(`received rm entry for unknown price lvl: ${price}`)
```
Comment (robertkowalski) [inline lib/models/order_book.js]: are we handling this somewhere? if not  it will crash people's bots

File: lib/transports/rest.js [hunk 5]
```diff
@@ -0,0 +1,386 @@
...
+      method: 'POST',
+      timeout: 15000,
+      headers: {
+        'X-BFX-APIKEY': this._apiKey,
+        'X-BFX-PAYLOAD': payloadBase64,
+        'X-BFX-SIGNATURE': sig
+      }
+    }, (err, response, body) => {
+      if (err || (response.statusCode !== 200 && response.statusCode !== 400)) {
+        return cb(new Error(err != null ? err : response.statusCode))
```
Comment (robertkowalski) [inline lib/transports/rest.js]: this is tricky because of the implicit bool conversion via `!=`

ok so we just get into this path if error is defined or if the status code does not fit. btw what is with HTTP `201`? Maybe test via regex: /^2../test(response.statusCode)

suggestion:

```js
if (err) return cb(err)
if (response.statusCode !== 200 && response.statusCode !== 400) return cb(new Error(response.statusCode))

// yada yada
```

File: lib/transports/rest.js [hunk 6]
```diff
@@ -0,0 +1,386 @@
...
+      }
+
+      let result
+
+      try {
+        result = JSON.parse(body)
+      } catch (error) {
+        return cb(null, {
+          message: body.toString()
+        })
```
Comment (robertkowalski) [inline lib/transports/rest.js]: wait a second...

given this returns a html cloudflare page...

the error is catched, and then the callback called with no error, but message as prop... this will break other peoples code...

File: lib/transports/rest.js [hunk 7]
```diff
@@ -0,0 +1,386 @@
...
+      }
+
+      if (result.message != null) {
```
Comment (robertkowalski) [inline lib/transports/rest.js]: strict equal please - or:

```js
if (result.message)
```

File: lib/transports/rest.js [hunk 8]
```diff
@@ -0,0 +1,386 @@
...
+        if (result.message.indexOf('Nonce is too small') !== -1) {
+          result.message += ' See https://github.com/bitfinexcom/bitfinex-api-node/blob/master/README.md#nonce-too-small for help'
+        }
+
+        return cb(new Error(result.message))
```
Comment (robertkowalski) [inline lib/transports/rest.js]: here an error with the message is returned (see comment at try catch)

File: lib/transports/rest.js [hunk 9]
```diff
@@ -0,0 +1,386 @@
...
+  }
+
+  make_public_request (path, cb) {
+    return request({
+      method: 'GET',
+      timeout: 15000,
+      url: `${this._url}/v1/${path}`
+    }, (err, response, body) => {
+      if (err || (response.statusCode !== 200 && response.statusCode !== 400)) {
+        return cb(new Error(err != null ? err : response.statusCode))
```
Comment (robertkowalski) [inline lib/transports/rest.js]: same error handling and non-strict-equal as above

File: lib/transports/rest.js [hunk 10]
```diff
@@ -0,0 +1,386 @@
...
+          message: body.toString()
+        })
+      }
+
+      // TODO: HTTP error code check?
+      if (result.message != null) {
+        return cb(new Error(result.message))
+      }
+
+      return cb(null, result)
```
Comment (robertkowalski) [inline lib/transports/rest.js]: same here in this block & the try / catch (see above comments)

File: lib/transports/rest2.js [hunk 11]
```diff
@@ -0,0 +1,239 @@
...
+    .then(this._doTransform.bind(this, modelClass))
+    .then(res => cb(null, res))
+    .catch(error => cb(new Error(error)))
+  }
+
+  _doTransform (modelClass, data) {
+    if (!data || data.length === 0) return []
+    if (!modelClass || !this._transform) return data
+
+    if (data[0].constructor.name === 'Array') {
```
Comment (robertkowalski) [inline lib/transports/rest2.js]: Array.isArray()

File: lib/transports/rest2.js [hunk 12]
```diff
@@ -0,0 +1,239 @@
...
+      return data.map(row => new modelClass(row))
```
Comment (robertkowalski) [inline lib/transports/rest2.js]: constructor functions should start uppercase

File: lib/transports/ws2.js [hunk 13]
```diff
@@ -0,0 +1,832 @@
...
+  requestCalc () {
+    throw new Error('unimplemented') // TODO
+  }
+
+  /**
+   * @param {Object|Array} order
+   * @return {Promise} p
+   */
+  submitOrder (order) {
+    if (!this._isAuthenticated) throw new Error('not authenticated')
```
Comment (robertkowalski) [inline lib/transports/ws2.js]: emit error instead?

Comment (robertkowalski) [reply lib/transports/ws2.js]: oh wait, we return a promise later. then retun a promise and reject it?

maybe like this?

```js
if (!this._isAuthenticated) return Promise.reject()

```

File: lib/transports/ws2.js [hunk 14]
```diff
@@ -0,0 +1,832 @@
...
+    this._sendOrderPacket([0, 'on', null, packet])
+
+    return this._getEventPromise(`order-${packet.cid}`)
+  }
+
+  /**
+   * @param {Object|Array|number} order
+   */
+  cancelOrder (order) {
+    if (!this._isAuthenticated) throw new Error('not authenticated')
```
Comment (robertkowalski) [inline lib/transports/ws2.js]: same here

Comment (robertkowalski) [reply lib/transports/ws2.js]: also check in later code, there are more throws

File: test/lib/transports/rest1.js [hunk 15]
```diff
@@ -0,0 +1,149 @@
...
+    it('should fail on authenticated requests if no api_key and api_secret', () => {
+      expect(bfx_rest.account_infos).to.throw(Error)
+    })
+  })
+
+  describe('public endpoints', function () {
+    const bfx_rest = new RESTv1()
+    this.timeout(10000) // bumped from 5k for moments of platform lag
+    it('should get a ticker', (done) => {
+      if (skipPublic) return done()
```
Comment (robertkowalski) [inline test/lib/transports/rest1.js]: <3

File: lib/models/order.js (hunk 3 above)
Comment (f3rno) [reply lib/models/order.js]: It's defined at the top of the file & not exposed; I did this since using `Date.now()` for the `cid` of two orders in rapid succession yields the same `cid`. This way at least the default is unique per run.

File: lib/models/order_book.js (hunk 4 above)
Comment (f3rno) [reply lib/models/order_book.js]: The data might be inconsistent due to dropped packets/network troubles; this would kill the bot there to prevent any issues. I switched it to a debug statement for now 🙈 What do you think about maybe clearing the OB if inconsistency is detected?

File: lib/transports/rest.js (hunk 6 above)
Comment (f3rno) [reply lib/transports/rest.js]: This was there before, heh: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/rest.js#L56

I'm returning the error now in all cases

File: lib/models/order.js (hunk 3 above)
Comment (robertkowalski) [reply lib/models/order.js]: ah makes sense!

**Comment by robertkowalski** [comment]
code looks good, impressive work.

please update the readme.md and changelog - after that +1

**Comment by skylinezum** [comment]
Hi, this PR seems to be the best bfx node client, but I've gotten some auth problems using this PR.
Just want to let you guys know. They both seem related to the nonce.

```
Error: invalid auth seq #; last 8, got 93762
```

```
{ event: 'auth',
  status: 'FAILED',
  chanId: 0,
  code: 10114,
  msg: 'nonce: small' }
```

**Comment by f3rno** [comment]
@skylinezum are you still seeing the nonce issue? Do you have a full packet log for the invalid sequence number message?

I've increased the nonce size in 99e8ea6, but I haven't been able to reproduce this issue myself.

**Comment by skylinezum** [comment]
I still get nonce is too small. The line `this._nonce = Date.now()` in rest.js and rest2.js should be `this._nonce = Date.now() * 1000`

**Comment by f3rno** [comment]
@skylinezum fixed :)
